version: '3.8'

services:
  web:
    image: sniper-yolo-backend:test
    container_name: fastapi_app_test
    ports:
      - "27051:8000"
    depends_on:
      - mongo
    env_file:
      - .env.test
    environment:
      - MONGODB_URL=mongodb://mongo:27017  # 确保使用容器互联地址

  mongo:
    image: mongo:5.0
    container_name: mongo_db_test
    volumes:
      - mongo_data_test:/data/db
    env_file:
      - .env.test

volumes:
  mongo_data_test:
    driver: local